#line 2 "tokens.cpp"

#line 4 "tokens.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[297] =
    {   0,
        0,    0,    0,    0,   99,   98,   94,    6,    6,   24,
       98,   23,   47,   98,   28,   27,   21,   19,   33,   20,
       34,   22,   92,   92,   42,   41,   15,   35,   17,   43,
       98,   93,   29,   30,   49,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   31,
       45,   32,   48,   98,    4,    5,   94,    6,   13,    0,
       95,    0,   46,    0,   97,    0,   38,   25,   36,   26,
       37,   92,    0,    0,    0,   39,    0,    0,   92,    0,
       50,   16,   11,   18,   51,   10,   10,   10,   10,   93,
       93,   93,   93,   93,   93,   93,   84,   93,   93,   93,

       93,   93,   93,   79,   93,   86,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       40,   44,    0,    4,   14,    0,    0,    0,    0,    0,
        0,    0,    2,   96,    0,    0,    0,   92,   92,   12,
       52,   10,   10,   10,   10,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   85,   93,   64,
       93,   93,   62,   93,   93,   93,   93,   93,   93,   65,
       93,   93,   93,   93,   93,   82,   78,   93,    0,   96,
        1,    0,   96,    0,    0,    0,    0,    8,   10,    9,
       93,   58,   93,   93,   93,   93,   93,   93,   93,   80,

       93,   93,   93,   93,   93,   93,   93,   61,   93,   93,
       93,   93,   93,   93,   93,   93,   72,   77,   93,    0,
        1,    7,   57,   83,   68,   75,   93,   93,   93,   93,
       93,   93,   93,   76,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   73,   93,   81,    0,   93,   93,
       93,   54,   91,   93,   93,   93,   93,   67,   93,   93,
       93,   93,   69,   56,   74,   60,    0,   93,   93,   59,
       87,   93,   93,   93,   93,   66,   70,   93,    0,   55,
       93,   89,   63,   93,   93,   93,    0,   90,   93,   93,
       71,    0,    3,   88,   53,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       30,   31,   32,   33,   29,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   29,   43,   44,   45,   46,
       47,   48,   29,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    2,    2,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    2,    1,    1,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[310] =
    {   0,
        0,  435,   60,   62,  441,  443,  438,  443,  436,  414,
       61,  443,  428,   59,  443,  443,  412,   56,  443,   55,
       53,   64,   64,   74,  443,  443,   51,  411,   72,  443,
       58,    0,  443,  443,  443,  385,   55,   62,   57,   69,
      395,   72,   68,   76,  394,   75,   37,  397,  389,  443,
       81,  443,  443,  387,    0,  443,  426,  443,  403,  108,
      443,  423,  443,  105,  443,  422,  443,  443,  443,  443,
      443,  103,  106,  117,  128,  115,  131,  122,  133,  139,
      443,  443,  400,  443,  398,    0,  384,  387,  382,    0,
      381,   93,  384,  371,  366,  112,    0,  365,  112,  370,

      364,  366,  360,    0,  362,  359,  354,  363,  370,  119,
      370,  353,  352,  368,  353,  358,  357,  113,  349,  355,
      443,  443,  350,    0,  443,  355,  166,  152,  132,  177,
      381,  151,  443,  178,  167,  169,  183,  169,  191,  443,
      443,    0,  342,  347,  340,  356,  351,  352,  337,  143,
      335,  351,  346,  345,  335,  343,  330,    0,  343,    0,
      152,  327,    0,  333,  333,  322,  323,  329,  320,    0,
      320,  332,  318,  318,  329,    0,    0,  322,  329,  443,
      324,  345,  349,  200,  184,  203,  219,    0,  323,    0,
      317,    0,  318,  308,  306,  314,  308,  302,  302,    0,

      303,  158,  313,  299,  311,  299,  313,    0,  312,  311,
      306,  301,  293,  299,  291,  303,    0,    0,  300,  293,
      443,    0,    0,    0,    0,    0,  290,  290,  290,  295,
      281,  294,  284,    0,  287,  283,  276,  280,  285,  273,
      287,  286,  275,  284,    0,  247,    0,  209,  208,  216,
      206,    0,    0,  205,  220,  206,  214,    0,  215,  211,
      210,  196,    0,    0,    0,    0,  209,  206,  185,    0,
        0,  194,  190,  187,  182,    0,    0,  174,  167,    0,
      165,    0,    0,  140,  117,  110,  233,    0,   88,   37,
        0,  239,  443,    0,    0,  443,  262,  267,  272,  277,

      278,  281,  286,  291,  296,  301,  304,  309,  314
    } ;

static yyconst flex_int16_t yy_def[310] =
    {   0,
      296,    1,  297,  297,  296,  296,  296,  296,  296,  296,
      298,  296,  296,  299,  296,  296,  296,  296,  296,  296,
      296,  300,  296,  296,  296,  296,  296,  296,  296,  296,
      301,  302,  296,  296,  296,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  296,
      296,  296,  296,  296,  303,  296,  296,  296,  296,  298,
      296,  298,  296,  299,  296,  299,  296,  296,  296,  296,
      296,  296,  300,  304,  305,  300,  306,  296,  296,  296,
      296,  296,  296,  296,  296,  307,  307,  307,  307,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      296,  296,  296,  303,  296,  296,  304,  304,  308,  309,
      308,  305,  296,  305,  300,  300,  306,  296,  296,  296,
      296,  307,  307,  307,  307,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  296,  296,
      296,  308,  308,  304,  304,  304,  309,  307,  307,  307,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  296,
      296,  307,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  296,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  296,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  296,  302,
      302,  302,  302,  302,  302,  302,  296,  302,  302,  302,
      302,  296,  296,  302,  302,    0,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296
    } ;

static yyconst flex_int16_t yy_nxt[505] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   33,
        6,   34,   35,   32,   36,   37,   38,   39,   40,   41,
       32,   42,   32,   32,   32,   43,   32,   44,   45,   46,
       47,   32,   48,   49,   32,   32,   32,   50,   51,   52,
       53,   56,   56,   56,   56,   56,   61,   56,   65,   68,
       70,   72,   72,   81,   82,  295,   74,  117,   71,   69,
       78,   75,   79,   79,   56,  118,   56,   76,   92,   66,
       78,   62,   79,   79,   77,   84,   85,   87,   93,   96,

       98,   94,  100,   88,  121,  107,   95,   89,   97,  109,
      104,   99,  113,   61,   65,  101,  105,  106,   80,  108,
      102,   72,   72,  126,  110,  114,  115,  111,  116,  128,
      133,  133,  126,   73,  129,   66,   77,  294,   62,  122,
      138,  138,  147,  148,  182,   77,  291,  130,  136,   78,
      152,   79,   79,  133,  133,  153,  131,  139,  139,  155,
      166,  137,  156,  290,  175,  167,  139,  134,  176,  181,
       73,  183,  139,  139,  139,  139,  139,  139,  128,  127,
      133,  133,  130,  129,  126,   73,  126,  138,  138,  185,
      289,  131,  195,  196,  186,  205,  130,   77,  206,   77,

      136,  181,  288,  232,  287,  131,  233,  187,  180,  139,
      139,  286,  128,  137,  130,  128,  127,  129,  139,  285,
      129,  127,   73,  131,  139,  139,  139,  139,  139,  139,
      130,  185,  284,  130,  292,  283,  186,  282,  293,  131,
      292,  281,  183,  280,  293,  279,  278,  277,  276,  187,
      275,  274,  273,  272,  271,  293,  270,  269,  127,  268,
      267,  293,   55,   55,   55,   55,   55,   60,   60,   60,
       60,   60,   64,   64,   64,   64,   64,   73,   73,   73,
       73,   86,   86,   90,   90,   90,  124,  266,  124,  124,
      124,  127,  127,  127,  127,  127,  132,  132,  132,  132,

      132,  135,  135,  135,  135,  135,  142,  142,  142,  131,
      131,  131,  131,  131,  184,  184,  184,  184,  184,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  182,  221,  180,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  204,  203,
      202,  201,  200,  199,  198,  197,  194,  193,  192,  191,
      190,  189,  188,  182,  180,  179,  178,  177,  174,  173,

      172,  171,  170,  169,  168,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  154,  151,  150,  149,  146,  145,
      144,  143,  141,  140,  296,  296,  125,   57,  123,  120,
      119,  112,  103,   91,   83,   67,   63,   59,   58,   57,
      296,   54,    5,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296
    } ;

static yyconst flex_int16_t yy_chk[505] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    3,   11,    4,   14,   18,
       20,   21,   21,   27,   27,  290,   22,   47,   20,   18,
       23,   22,   23,   23,    3,   47,    4,   22,   37,   14,
       24,   11,   24,   24,   22,   29,   29,   31,   37,   38,

       39,   37,   40,   31,   51,   43,   37,   31,   38,   44,
       42,   39,   46,   60,   64,   40,   42,   42,   23,   43,
       40,   72,   72,   73,   44,   46,   46,   44,   46,   74,
       75,   75,   76,   77,   74,   64,   73,  289,   60,   51,
       78,   78,   92,   92,  129,   76,  286,   74,   77,   79,
       96,   79,   79,  132,  132,   96,   74,   80,   80,   99,
      110,   77,   99,  285,  118,  110,   80,   75,  118,  128,
       77,  129,   80,   80,   80,   80,   80,   80,  127,  130,
      134,  134,  128,  127,  135,  137,  136,  138,  138,  130,
      284,  128,  150,  150,  130,  161,  127,  135,  161,  136,

      137,  185,  281,  202,  279,  127,  202,  130,  136,  139,
      139,  278,  184,  137,  185,  186,  130,  184,  139,  275,
      186,  187,  137,  185,  139,  139,  139,  139,  139,  139,
      184,  187,  274,  186,  287,  273,  187,  272,  287,  184,
      292,  269,  186,  268,  292,  267,  262,  261,  260,  187,
      259,  257,  256,  255,  254,  287,  251,  250,  187,  249,
      248,  292,  297,  297,  297,  297,  297,  298,  298,  298,
      298,  298,  299,  299,  299,  299,  299,  300,  300,  300,
      300,  301,  301,  302,  302,  302,  303,  246,  303,  303,
      303,  304,  304,  304,  304,  304,  305,  305,  305,  305,

      305,  306,  306,  306,  306,  306,  307,  307,  307,  308,
      308,  308,  308,  308,  309,  309,  309,  309,  309,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  233,
      232,  231,  230,  229,  228,  227,  220,  219,  216,  215,
      214,  213,  212,  211,  210,  209,  207,  206,  205,  204,
      203,  201,  199,  198,  197,  196,  195,  194,  193,  191,
      189,  183,  182,  181,  179,  178,  175,  174,  173,  172,
      171,  169,  168,  167,  166,  165,  164,  162,  159,  157,
      156,  155,  154,  153,  152,  151,  149,  148,  147,  146,
      145,  144,  143,  131,  126,  123,  120,  119,  117,  116,

      115,  114,  113,  112,  111,  109,  108,  107,  106,  105,
      103,  102,  101,  100,   98,   95,   94,   93,   91,   89,
       88,   87,   85,   83,   66,   62,   59,   57,   54,   49,
       48,   45,   41,   36,   28,   17,   13,   10,    9,    7,
        5,    2,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.l"
/*
 tokens.l
 Compressor
 
 Created by Orlando Leite on 10/10/12.
 Copyright 2011. All rights reserved.
 
 This file is part of Compressor.
 
 Compressor is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 Compressor is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with Compressor.  If not, see <http://www.gnu.org/licenses/>.
 */
#line 26 "tokens.l"
	#include <iostream>
	#include "types.hpp"
	#include "expressions.hpp"
	#include "instructions.hpp"
	#include "blocks.hpp"
	#include "workspace.hpp"
	#include "parser.hpp"
	
	#define TOKEN(t) yylval.tinfo = new TokenInfo( t, curbs->lineno, *new std::string(), *new std::string( curbs->filename, strlen( curbs->filename ) ) )
	#define SAVE_TOKEN(a, t, l) \
		yylval.tinfo = new TokenInfo( a, \
									  yylineno, \
									  *new std::string(t, l), \
									  *new std::string( curbs->filename, strlen( curbs->filename ) ) \
									);
	
	unsigned int linenum = 0;
	
	extern int newfile(const char *fn, const char *rn);
	extern int popfile(void);
	
	struct bufstack
	{
		struct bufstack *prev;
		YY_BUFFER_STATE bs;
		int lineno;
		
		const char *filename;
		const char *realFilename;
		FILE *f;
	} *curbs = 0;


#line 724 "tokens.cpp"

#define INITIAL 0
#define IFILE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "tokens.l"


#line 913 "tokens.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 297 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 443 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 64 "tokens.l"
{ ; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 65 "tokens.l"
{ ; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "tokens.l"
{ BEGIN IFILE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "tokens.l"
{
{
	int c;
	while((c = yyinput()) && c != '\n');
}

yylineno++;
// if(!newfile(yytext)) yyterminate();
/* no such file */
BEGIN INITIAL;
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 79 "tokens.l"
{
fprintf(stderr, "%4d bad include line\n", yylineno);
yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 83 "tokens.l"
{ /*if(!popfile()) TOKEN(TEOF); return TEOF;*/ yyterminate(); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 85 "tokens.l"
{ ++yylineno; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "tokens.l"
{ TOKEN(TCOMPNAME); return TCOMPNAME; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "tokens.l"
{ TOKEN(TCOMPGET); return TCOMPGET; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "tokens.l"
{ TOKEN(TCOMPSET); return TCOMPSET; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "tokens.l"
{ SAVE_TOKEN( TCOMPVAR, yytext, yyleng ); return TCOMPVAR; /* currently not used */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "tokens.l"
{ TOKEN(TEQ); return TEQ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 93 "tokens.l"
{ TOKEN(TEQA); return TEQA; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "tokens.l"
{ TOKEN(TNE); return TNE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "tokens.l"
{ TOKEN(TNEA); return TNEA; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "tokens.l"
{ TOKEN(TLT); return TLT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "tokens.l"
{ TOKEN(TLE); return TLE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "tokens.l"
{ TOKEN(TGT); return TGT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "tokens.l"
{ TOKEN(TGE); return TGE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "tokens.l"
{ TOKEN(TPLUS); return TPLUS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "tokens.l"
{ TOKEN(TMINUS); return TMINUS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "tokens.l"
{ TOKEN(TMULT); return TMULT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "tokens.l"
{ TOKEN(TDIVIDE); return TDIVIDE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "tokens.l"
{ TOKEN(TMODULUS); return TMODULUS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 105 "tokens.l"
{ TOKEN(TNOT); return TNOT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "tokens.l"
{ TOKEN(TINCREMENT); return TINCREMENT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "tokens.l"
{ TOKEN(TDECREMENT); return TDECREMENT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "tokens.l"
{ TOKEN(TRPAREN); return TRPAREN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "tokens.l"
{ TOKEN(TLPAREN); return TLPAREN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "tokens.l"
{ TOKEN(TLBRACKET); return TLBRACKET; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "tokens.l"
{ TOKEN(TRBRACKET); return TRBRACKET; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "tokens.l"
{ TOKEN(TLBRACE); return TLBRACE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "tokens.l"
{ TOKEN(TRBRACE); return TRBRACE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "tokens.l"
{ TOKEN(TCOMMA); return TCOMMA; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "tokens.l"
{ TOKEN(TDOT); return TDOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "tokens.l"
{ TOKEN(TASSIGN); return TASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "tokens.l"
{ TOKEN(TASSIGN_PLUS); return TASSIGN_PLUS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "tokens.l"
{ TOKEN(TASSIGN_MINUS); return TASSIGN_MINUS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "tokens.l"
{ TOKEN(TASSIGN_MULTIPLY); return TASSIGN_MULTIPLY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "tokens.l"
{ TOKEN(TASSIGN_DIVIDE); return TASSIGN_DIVIDE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "tokens.l"
{ TOKEN(TASSIGN_BOR); return TASSIGN_BOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "tokens.l"
{ TOKEN(TSEMICOLON); return TSEMICOLON; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "tokens.l"
{ TOKEN(TCOLON); return TCOLON; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "tokens.l"
{ TOKEN(TQUESTION); return TQUESTION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "tokens.l"
{ TOKEN(TOR); return TOR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "tokens.l"
{ TOKEN(TBOR); return TBOR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "tokens.l"
{ TOKEN(TAND); return TAND; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "tokens.l"
{ TOKEN(TBAND); return TBAND; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "tokens.l"
{ TOKEN(TBNOT); return TBNOT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "tokens.l"
{ TOKEN(TBXOR); return TBXOR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 131 "tokens.l"
{ TOKEN(TLSHIFT); return TLSHIFT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 132 "tokens.l"
{ TOKEN(TRSHIFT); return TRSHIFT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 133 "tokens.l"
{ TOKEN(TZFILL); return TZFILL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 134 "tokens.l"
{ TOKEN(TINSTANCEOF); return TINSTANCEOF; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 135 "tokens.l"
{ TOKEN(TDELETE); return TDELETE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 136 "tokens.l"
{ TOKEN(TQUESTION); return TCONTINUE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 137 "tokens.l"
{ TOKEN(TRETURN); return TRETURN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 138 "tokens.l"
{ TOKEN(TBREAK); return TBREAK; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 139 "tokens.l"
{ TOKEN(TCASE); return TCASE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 140 "tokens.l"
{ TOKEN(TDEFAULT); return TDEFAULT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 141 "tokens.l"
{ TOKEN(TSWITCH); return TSWITCH; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 142 "tokens.l"
{ TOKEN(TNULL); return TNULL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 143 "tokens.l"
{ TOKEN(TNEW); return TNEW; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 144 "tokens.l"
{ TOKEN(TFUNCTION); return TFUNCTION; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 145 "tokens.l"
{ TOKEN(TGET); return TGET; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 146 "tokens.l"
{ TOKEN(TSET); return TSET; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 147 "tokens.l"
{ TOKEN(TPACKAGE); return TPACKAGE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 148 "tokens.l"
{ TOKEN(TIMPORT); return TIMPORT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 149 "tokens.l"
{ TOKEN(TCLASS); return TCLASS; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 150 "tokens.l"
{ TOKEN(TPUBLIC); return TPUBLIC; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 151 "tokens.l"
{ TOKEN(TPRIVATE); return TPRIVATE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 152 "tokens.l"
{ TOKEN(TPROTECTED); return TPROTECTED; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 153 "tokens.l"
{ TOKEN(TTHIS); return TTHIS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 154 "tokens.l"
{ TOKEN(TSUPER); return TSUPER; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "tokens.l"
{ TOKEN(TSTATIC); return TSTATIC; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "tokens.l"
{ TOKEN(TCONST); return TCONST; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 157 "tokens.l"
{ TOKEN(TFALSE); return TFALSE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 158 "tokens.l"
{ TOKEN(TTRUE); return TTRUE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 159 "tokens.l"
{ TOKEN(TVAR); return TVAR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 160 "tokens.l"
{ TOKEN(TIF); return TIF; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 161 "tokens.l"
{ TOKEN(TELSE); return TELSE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "tokens.l"
{ TOKEN(TWHILE); return TWHILE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "tokens.l"
{ TOKEN(TTRY); return TTRY; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "tokens.l"
{ TOKEN(TCATCH); return TCATCH; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "tokens.l"
{ TOKEN(TDO); return TDO; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "tokens.l"
{ TOKEN(TFOR); return TFOR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 167 "tokens.l"
{ TOKEN(TIN); return TIN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "tokens.l"
{ TOKEN(TEXTENDS); return TEXTENDS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "tokens.l"
{ TOKEN(TIMPLEMENTS); return TIMPLEMENTS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 170 "tokens.l"
{ TOKEN(TEXTERNAL); return TEXTERNAL; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 171 "tokens.l"
{ TOKEN(TCUSTOMIZE); return TCUSTOMIZE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 172 "tokens.l"
{ TOKEN(TEXPORT); return TEXPORT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 173 "tokens.l"
{ 
	SAVE_TOKEN( TNUMBER, yytext, yyleng );
	return TNUMBER;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 177 "tokens.l"
{
	SAVE_TOKEN( TNAME, yytext, yyleng );
	return TNAME;
}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 181 "tokens.l"
{ ; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 182 "tokens.l"
{
	SAVE_TOKEN( TSTRING, yytext, yyleng );
	return TSTRING;
}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 186 "tokens.l"
{
	SAVE_TOKEN( TREGEX, yytext, yyleng );
	return TSTRING;
}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 190 "tokens.l"
{
SAVE_TOKEN( TSTRING, yytext, yyleng );
return TSTRING;
}
	YY_BREAK
/*\        { ; }
\n       { nextline(); }
\t       { ; }
"//".*\n { nextline(); }
.        { yyerror("illegal token"); }

[0-9]+		{ yylval = atoi(yytext); return TNUMERO; }
"+"		return OP_SOMA;
"-"		return OP_SUB;
"*"		return OP_MULT;
"/"		return OP_DIV;* /
%}
[ \t]+
[\r\n]		{ return TEOL;
	/* NAO usar [\r\n]+ senao ele fica 'a espera
	 do proximo caracter apos o Enter!!
	 Note-se que um EOL do Windows ("\r\n")
	 faz gerar dois tokens EOL * /
	 }*/

case 98:
YY_RULE_SETUP
#line 215 "tokens.l"
ECHO;
	YY_BREAK
#line 1548 "tokens.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 297 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 297 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 296);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 215 "tokens.l"



const char *curfilename;

int newfile( const char *fn, const char *realPath )
{
	FILE *f = fopen(fn, "r");
	
	bufstack *bs = new bufstack();
	/* die if no file or no room */
	if(!f) {
		perror(fn);
		return 0;
	}
	
	if(!bs) {
		perror("malloc"); exit(1);
	}
	
	/* remember state */
	if(curbs)curbs->lineno = yylineno;
	bs->prev = curbs;
	/* set up current entry */
	bs->bs = yy_create_buffer(f,YY_BUF_SIZE);
	
	bs->f = f;
	bs->realFilename = realPath;
	bs->filename = realPath;
	
	// std::cout << fn << std::endl;
	
	yy_switch_to_buffer(bs->bs);
	curbs = bs;
	yylineno = 1;
	currentFile = realPath;
	curfilename = fn;
	
	return 1;
}

int popfile(void)
{
	struct bufstack *bs = curbs;
	struct bufstack *prevbs;
	if(!bs) return 0;
	/* get rid of current entry fclose(bs->f); yy_delete_buffer(bs->bs);
	 /* switch back to previous */
	prevbs = bs->prev;
	free(bs);
	if(!prevbs) return 0;
	yy_switch_to_buffer(prevbs->bs); curbs = prevbs;
	yylineno = curbs->lineno;
	curfilename = curbs->filename;
	currentFile = curbs->realFilename;
	
	return 1;
}

